name: Deploy via SCP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy website files via SFTP
        uses: hrsetyono/git-sftp-action@v4
        with:
          url: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          port: 30
          key: ${{ secrets.ACTION_SSH_KEY }}
          syncroot: "src/"
